# Generated by Django 5.0.3 on 2024-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_year', models.IntegerField()),
                ('diastolic_pressure', models.IntegerField()),
                ('systolic_pressure', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('glucose_ac', models.IntegerField()),
                ('hba1c', models.FloatField()),
                ('t_cho', models.IntegerField()),
                ('tg', models.IntegerField()),
                ('hdl_c', models.IntegerField()),
                ('ldl_c', models.IntegerField()),
                ('abstract', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
